spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://postgres:5432/parking_db
    username: parking_user
    password: parking@1
    driverClassName: org.postgresql.Driver